cn:
  daocloud:
    token:

server.port: 9082

spring.jpa.hibernate.ddl-auto: update
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cherrynic?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&verifyServerCertificate=false
    username: root
    password: root
    initialSize: 1
    maxActive: 50
    maxIdle: 50
    maxWait: 120000
    minIdle: 5
    validationQuery: SELECT 1 FROM DUAL
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
